sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
before_script:
  - pip install --user codecov
language: java
install: mvn clean install
after_success:
- echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>"
  > ~/settings.xml
- if [ -z ${TRAVIS_TAG} ]; then mvn deploy --settings ~/settings.xml; fi
